# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"seed_everything": "00_core.ipynb"}

modules = ["core.py",
           "imagewoof.py"]

doc_url = "https://manisnesan.github.io/fastchai/"

git_url = "https://github.com/manisnesan/fastchai/tree/master/"

def custom_doc_links(name): return None
