# AUTOGENERATED! DO NOT EDIT! File to edit: 03_hasoc_en.ipynb (unless otherwise specified).

__all__ = ['load_data', 'get_dataloaders', 'train', 'predict']

# Cell
from fastchai import config

# Cell
from fastai.text.all import *
from pathlib import Path

# Cell
def load_data(path:Path)->pd.DataFrame:
    pass

# Cell
def get_dataloaders(all:pd.DataFrame, is_lm:bool, config)->DataLoaders:
    pass

# Cell
from fastai.learner import Learner

def train(
        dls:DataLoaders,
        is_lm:bool,
        config)->Learner:

    if is_lm:
        pass
    else:
        pass

# Cell
from fastai.learner import Learner
from fastai.data.all import DataLoaders

from typing import List

def predict(learn:Learner, dls:DataLoaders)->List[str]:
    pass